### ISSUE TITLE
Update OSF repo

### ISSUE THREAD

**Issue by sloria** [CenterForOpenScience/COSDev#17]
The OSF repo URL is wrong in at least one place: http://cosdev.readthedocs.org/en/latest/osf/setup.html#clone-or-copy-the-osf-files-to-local-directory . These URLs need to be updated.

**Comment by lbanner** [comment]
@sloria How do we update said docs?

**Comment by sloria** [comment]
@lbanner At the top of a page, click "Edit on GitHub", which will take you to the corresponding source page on GitHub. Then click the little pencil icon to edit the file directly on GitHub. Then send a PR.

**Comment by lbanner** [comment]
TY @sloria
