### ISSUE TITLE
Problems with "Setting up the OSF" page

### ISSUE THREAD

**Issue by PatrickEGorman** [CenterForOpenScience/COSDev#21]
I'm trying to set up the OSF for my internship and I'm already a problem in your dev page.

In the section "Run OSF installation", the page tells you to input the following commands
```terminal
cd osf
pip install -r dev-requirements.txt
```

I might be doing something wrong but as far as I can tell, the directory osf does not exist.  Did you mean osf.io?  Also in osf.io dev-requirements.txt does not exist.  Did you mean requirements.txt?  I notice in your requirements folder there are a few other requirements to install.  Does one simply install all of them?

I am still working on setting up the osf and would really like to get it running by Monday, but due to lack of knowledge of numerous tools and a vague description of how to do things, I'm not sure.  It might be good to invest some time in this page as I'm sure I'm not the only intern who will find difficulty with this.

**Comment by brianjgeiger** [comment]
The expectation is that you will have created a directory on your computer called `osf` and that's where you will have cloned your github repo. In case the instructions don't mention, you will also want to set up a virtualenv before you pip install anything.

**Comment by PatrickEGorman** [comment]
Okay.  I have the virtualenv and seem to be figuring out things okay.  I'll let you know if I get really stuck on anything.  Thanks!
