### ISSUE TITLE
[OSF Set Up]  Setting file changed and need new command?

### ISSUE THREAD

**Issue by haoyuchen1992** [CenterForOpenScience/COSDev#27]
When I pull the update from osf, it gave me error:
![screen shot 2015-06-17 at 10 33 09 am](https://cloud.githubusercontent.com/assets/5420789/8209696/6af48b10-14dc-11e5-86e0-609a065f16b7.png)

After I run the command -- `cp api/base/settings/local-dist.py api/base/settings/local.py`, then it is fine. But I remember the command in docs was `cp website/settings/local-dist.py website/settings/local.py`.

Does it mean the old one has been replaced, or we need run both commands when running osf?

**Comment by sloria** [comment]
Both `local.py` files are needed. I've updated the docs to clarify this.
